[package]
name = "cods-cli"
version = "0.1.0"
authors = ["Saecki <tobiasschmitz2001@gmail.com>"]
description = "A cli calculator"
edition = "2018"

[[bin]]
name = "cods"
path = "src/main.rs"

[dependencies]
cods = { path = "../cods" }
