[package]
name = "cods-cli"
version = "0.2.0"
authors = ["Saecki <tobiasschmitz2001@gmail.com>"]
description = "A cli calculator"
edition = "2021"

[[bin]]
doc = false
name = "cods"
path = "src/main.rs"

[dependencies]
cods = { path = "../cods" }
unicode-width = "0.1.9"
