[package]
name = "cods"
version = "0.2.0"
authors = ["Saecki <tobiasschmitz2001@gmail.com>"]
description = "Text based calculator engine"
edition = "2021"

[lib]
name = "cods"

[dependencies]
strum = { version = "0.24.0", features = ["derive"] }
