[package]
name = "cods"
version = "0.2.0"
authors = ["Saecki <tobiasschmitz2001@gmail.com>"]
description = "A statically typed scripting language"
edition = "2021"

[lib]
name = "cods"

[dependencies]
once_cell = { version = "1.13.0", default_features = false }
cods-derive = { path = "../derive" }
